services:
  database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    restart: always
  
  api01: &api
    hostname: api01
    image: paulomg96/challenge-makesai:1.0
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@database:5432/app_db
  
  api02:
    <<: *api
    image: paulomg96/challenge-makesai:1.0
    hostname: api02
    ports:
      - "8082:8000"
    depends_on:
     - database

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 

volumes:
  pgdata: